/*! Palm Court (c) 2026. All rights reserved. */
const o=n=>String(n??"").replace(/[&<>"']/g,e=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[e]),l=`
.ask { position: fixed; inset: 0; z-index: 95; display: grid; place-items: center; padding: 16px; background: rgba(4,9,15,.7); }
.ask[hidden] { display: none; }
.ask-card { width: min(520px, 100%); box-sizing: border-box; padding: 20px 22px 18px; background: #0c1a28; border: 1px solid var(--optic, #d6f04a); border-radius: 12px; display: grid; gap: 16px; }
.ask-card p { margin: 0; font: 600 18px/1.4 var(--body, system-ui, sans-serif); color: var(--chalk, #f2f5ee); white-space: pre-line; overflow-wrap: anywhere; }
.ask-card .row { display: flex; flex-wrap: wrap; gap: 10px; justify-content: flex-end; }
`;export const Ask={el:null,trigger:null,resolve:null,back:null,get isOpen(){return!!this.el&&!this.el.hidden},build(){if(this.el)return;const n=document.createElement("style");n.id="askCss",n.textContent=l,document.head.append(n);const e=document.createElement("div");e.className="ask",e.id="askCard",e.hidden=!0,e.dataset.modal="",e.setAttribute("role","alertdialog"),e.setAttribute("aria-modal","true"),e.setAttribute("aria-labelledby","askText"),e.innerHTML='<div class="ask-card"><p id="askText"></p><div class="row"><button type="button" class="btn" id="askNo" data-back>Cancel</button><button type="button" class="btn primary" id="askYes">OK</button></div></div>',document.body.append(e),this.el=e,e.querySelector("#askYes").onclick=()=>this.answer(!0),e.querySelector("#askNo").onclick=()=>this.answer(!1),e.addEventListener("keydown",t=>{t.key==="Escape"&&(t.stopPropagation(),t.preventDefault(),this.answer(!1))})},open(n,{yes:e="OK",no:t="Cancel"}={}){this.build(),this.resolve&&this.answer(!1),this.back=document.activeElement,this.el.querySelector("#askText").textContent=String(n??"");const r=this.el.querySelector("#askYes"),s=this.el.querySelector("#askNo");return r.textContent=e,s.textContent=t,s.hidden=!t,this.el.hidden=!1,(t?s:r).focus({preventScroll:!0}),new Promise(i=>{this.resolve=i})},answer(n){if(!this.el||this.el.hidden)return;this.el.hidden=!0;const e=this.resolve,t=this.back;this.resolve=null,this.back=null,t&&t.isConnected&&t.focus({preventScroll:!0}),e&&e(!!n)},install(n){if(this.installed||typeof window>"u")return;this.installed=!0;const e=window.confirm.bind(window),t=window.prompt.bind(window);let r=null;window.confirm=s=>{const i=this.trigger;return r&&r===i?(r=null,!0):!i||!n()?e(s):(this.open(s).then(a=>{if(a&&i.isConnected){r=i,this.trigger=i;try{i.click()}finally{r=null,this.trigger=null}}}),!1)},window.prompt=(s,i)=>!this.trigger||!n()?t(s,i):(this.open(`${s}
${i??""}`,{yes:"OK",no:""}),null)}};
